# PMM 镜像源配置 (mirror.conf 与本文件格式相同)
# apt 式：priority 越小越优先；default=true 为未显式指定时的默认镜像。
#
[sz]
registry = https://sz.pmm.parlz.com/mirror/packages
priority = 1
default = true

[main]
registry = https://pmm.parlz.com/mirror/packages
priority = 20
